### ISSUE TITLE
Conflict with input()

### ISSUE THREAD

**Issue by ChristophGaukel** [FuturisticGoo/maskpass#1]
When I first call input, eg.:
uid = input('Enter your User Id :')

and then call advpass, e.g.:
pwd = maskpass.advpass('Enter your Password:')

then the masking does not work correctly and I see:
m*y*s*e*c*r*e*t*

Kind regards
Christoph

**Comment by FuturisticGoo** [comment]
Could you specify the OS, Python version and IDLE used? I'm not able to replicate the issue with the given example as it works as expected. Currently I have tested it only in Windows Spyder/QtConsole, cmd, xfce terminal and zsh so there might be bugs.
Also, it might have been because Ctrl key was pressed, as it reveals the entered password.

**Comment by FuturisticGoo** [comment]
I'm going to close this issue because of inactivity. If you need help, please do not hesitate to reopen the issue.

**Comment by PominausGH** [comment]
Try pwd = maskpass.advpass() instaed off pwd = maskpass.advpass('Enter your Password:')

**Comment by FuturisticGoo** [comment]
@PominausGH That shouldn't be happening, can you give an example code which triggers this issue
